### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ythlev** [Semi-ATE/STDF#17]
It would be helpful to include what the output of a parsed STDF looks like.

**Comment by nerohmot** [comment]
@seimit I think that is indeed a good idea

**Comment by nerohmot** [comment]
@ythlev bare with us, soon we have the QScreenCast module running in spyder, then we will make tutorial video's 😋

**Comment by nerohmot** [comment]
@ythlev, we added examples, hope it is useful for you.

**Comment by seimit** [comment]
Closed after adding examples in the README file.
