### ISSUE TITLE
Code example doesn't work

### ISSUE THREAD

**Issue by busile** [Semi-ATE/STDF#18]
### Tasks/Steps/Elements
I ran the code from readme:

from Semi_ATE import STDF

for REC in STDF.records_from_file("blahbla.stdf"):
    print(REC)

I get the following error:
Traceback (most recent call last):
  File "C:_GIT\python_scripts\stdf_parser\stdf_parser.py", line 21, in <module>
    write_atdf(r"debug.std")
  File "C:\_GIT\Python\python_scripts\stdf_parser\stdf_parser.py", line 16, in write_atdf
    for REC in STDF.records_from_file(stdf_path):
AttributeError: module 'Semi_ATE.STDF' has no attribute 'records_from_file'

### Versions checklist

Semi-ATE version: 0.1.13
Python version: 3.92
Operating System name/version:
  - client : Windows 10

**Comment by nerohmot** [comment]
@seimit, can you take a look and update the README.md if needed?

**Comment by RemiVen** [comment]
Hi Tom, I also face the same issue using semi-ate-stdf 0.1.14 (standalone) with python 3.8.5. From what I see in Spyder, STDF module has : all records as class + os and utils modules but no records_from_file. Any ideas ?
