### ISSUE TITLE
Minor typos when converting STDF to ATDF

### ISSUE THREAD

**Issue by erikwelsh** [Semi-ATE/STDF#24]
### Tasks/Steps/Elements

There are two minor typos in files when trying to convert between STDF and ATDF.  Using the code from the example:

from Semi_ATE import STDF

basename = "blahblah"

with open(f"{basename}.atdf", "w") as atdf:
   for REC in STDF.records_from_file(f"{basename}.stdf"):
       atdf.write(REC.to_atdf())

1) Traceback (most recent call last):
  File "process_stdf.py", line 7, in <module>
    atdf.write(REC.to_atdf())
  File "/home/octavo/.local/lib/python3.8/site-packages/Semi_ATE/STDF/PTR.py", line 142, in to_atdf
    if sv[7] == '0':
NameError: name 'sv' is not defined

Resolution:  Instead of 'sv', the variable should just be 'v'

2) Traceback (most recent call last):
  File "process_stdf.py", line 7, in <module>
    atdf.write(REC.to_atdf())
  File "/home/octavo/.local/lib/python3.8/site-packages/Semi_ATE/STDF/PRR.py", line 107, in to_atdf
    buff += ' |'
UnboundLocalError: local variable 'buff' referenced before assignment

Resolution:  Instead of 'buff', the variable should be 'body'

Thanks for developing this software.  It is very useful.

### Versions checklist
* Semi-ATE-STDF:  0.1.15
* Python version: 3.8.5
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (WSL)

**Comment by seimit** [comment]
Hello Erik
Thank you for reporting the issue!
Could you please get the latest version from the main and try it?
Thanks in advance!
Seimit
