### ISSUE TITLE
Bug during pip install

### ISSUE THREAD

**Issue by steverlc** [Semi-ATE/STDF#28]
### Tasks/Steps/Elements
pip install Semi-ATF-STDF

code in file.py:
fl = "someFile"
from Semi_ATE import STDF
with open(f"{fl}.atdf", "w") as atdf:
   for REC in STDF.records_from_file(f"{fl}.stdf"):
       atdf.write(REC.to_atdf())

run :
python file.py

output:
File "C:\Python39\lib\site-packages\Semi_ATE\STDF\PTR.py", line 142, in to_atdf
    if sv[7] == '0':
NameError: name 'sv' is not defined

Seems like a typo? ("sv" should just be "v") When I pulled the code from git, the typo isn't there

### Versions checklist

* Spyder version: >= 5
* Python version: 3.9
* Operating System name/version:
  - client : Windows 10

**Comment by seimit** [comment]
Hello,
This was fixed in issue #24, but I forgot to make a release.
I already start the new release.
Best Regards
Seimit
