### ISSUE TITLE
ATDF MIR structure and datetime format issues

### ISSUE THREAD

**Issue by marilang** [Semi-ATE/STDF#36]
Thanks for this awesome package!
Found some issues in conversion to ATDF (which I realize is not the primary mission of this software.)
1) Inconsistent MIR structure. Field order matches STDF spec, not the ATDF spec like the FAR and ATR are following.
2) Time formatting: setup time and start time show minutes that are not zero filled.

### Tasks/Steps/Elements

Using sample code on PyPI project description page:

    with open(f"{basename}.atdf", "w") as atdf:
        for REC in STDF.records_from_file(f"{basename}.stdf.gz"):
            atdf.write(REC.to_atdf() + line_terminator)

First 3 records found in .atdf file: *most field data has been replaced by its field name to remove company info*

FAR:A|4|2|U

ATR:16:3:54 14-DEC-2021|CMD_LINE

MIR:16:2:45 14-DEC-2021|16:3:54 14-DEC-2021|1| |N| |65535| |LOT_ID||NODE_NAM|TSTR_TYP|JOB_NAM|JOB_REV|SBLOT_ID|OPER_NAM|EXEC_TYP|EXEC_VER||||||||||||||||||||

### Versions checklist

Semi-ATE-STDF version 1.18 
Jupyter notebook version 6.0.1

**Comment by seimit** [comment]
Hello Marilyn 
Thanks for reporting the issue!
I will check the specification and will try to fix it tomorrow.
Best Regards.
Seimit

**Comment by seimit** [comment]
Dear Marilyn,
Could you try the latest version if it fixes your issue?
Thanks in advance!
Seimit

**Comment by marilang** [comment]
Hi Seimit,

Thank you for the quick fix! and also for the new argument and the information about the treatment of insignificant zeroes in the ATDF spec. I tried a couple of (apparently ineffective) ways to upgrade, but my notebook is still loading v 1.18. I will figure it out eventually, but there will be some delay in my response. Sorry.

Best regards,
Marilyn

**Comment by seimit** [comment]
I forgot to push it in pip/conda. 
I'm going to do now. Not sure when will be available.
Regards,
Seimit

**Comment by marilang** [comment]
That will make it easy for me. :) Thanks. Eventually I will be able to install a version pulled or downloaded from Github but I'm not there yet.

**Comment by marilang** [comment]
Hi Seimit,

Thanks for publishing the update. The field order is still inconsistent with most records (like PTR and PRR) using ATDF spec, but MIR is in the STDF order.

I also noticed another new issue in the PTR record, below. Looks like 2 fields are within the same delimiter.


First, here’s my MIR record from version 1.19

MIR:10:17:0 10-DEC-2021|10:17:44 10-DEC-2021|1| |N| |65535| |<lot id>||<station name>|93000-SOC|<job nam>|<job rev>|<sblot id>|<oper nam>|93000|s/w rev. 7.3.2.5 (T), 01-Jul-15||||||||||||||||||||

You can see this order of fields is from the STDF spec.

***@***.***














This is different behavior from other fields.

For example, PTR output is following the ATDF order, and uses character codes for  Pass/fail and Alarm.  (although *new issue* it looks like both codes are appearing in the Pass/Fail field).

PTR:321|1|1|-0.6852759718894958|PP| ***@***.***_MZDCR_47[1]||  ||0.0|0.0||||0.0|0.0|0|0|0

***@***.***
***@***.***


Best regards,
Marilyn


--
Marilyn Langley, Cisco Systems

**Comment by marilang** [comment]
Hi again Seimit,

I’m so sorry for my error! I pip installed the new version and neglected to restart my kernel. The field order, as you know, is definitely fixed.  Thank you!

MIR:<lot id>||<job nam>/<part typ>|<node id>|93000-SOC|10:17:0 10-DEC-2021|10:17:44 10-DEC-2021|<oper nam>| |1|<sblot id>||N|0.9|93000|s/w rev. 7.3.2.5 (T), 01-Jul-15| | |65535|||||||||||||||||||


But the PTR still has the double P in a single field.

PTR:422|1|1|-0.7333530187606812|PP| ***@***.***_IFF_34[1]||  ||0.0|0.0||||0.0|0.0|0|0|0


Best regards,
Marilyn


--
Marilyn Langley, Cisco Systems


From: Marilyn Langley (marlangl)
Sent: Tuesday, December 21, 2021 10:22 AM
To: 'Semi-ATE/STDF' ***@***.***>; Semi-ATE/STDF ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Semi-ATE/STDF] ATDF MIR structure and datetime format issues (Issue #36)

Hi Seimit,

Thanks for publishing the update. The field order is still inconsistent with most records (like PTR and PRR) using ATDF spec, but MIR is in the STDF order.

I also noticed another new issue in the PTR record, below. Looks like 2 fields are within the same delimiter.


First, here’s my MIR record from version 1.19

MIR:10:17:0 10-DEC-2021|10:17:44 10-DEC-2021|1| |N| |65535| |<lot id>||<station name>|93000-SOC|<job nam>|<job rev>|<sblot id>|<oper nam>|93000|s/w rev. 7.3.2.5 (T), 01-Jul-15||||||||||||||||||||

You can see this order of fields is from the STDF spec.

***@***.***














This is different behavior from other fields.

For example, PTR output is following the ATDF order, and uses character codes for  Pass/fail and Alarm.  (although *new issue* it looks like both codes are appearing in the Pass/Fail field).

PTR:321|1|1|-0.6852759718894958|PP| ***@***.***_MZDCR_47[1]||  ||0.0|0.0||||0.0|0.0|0|0|0

***@***.***
***@***.***


Best regards,
Marilyn


--
Marilyn Langley, Cisco Systems

**Comment by seimit** [comment]
Hi again,
Definitely the value should be a single char because the field is named "Pass/Fail Flag". For example the next field is named "Alarm Flags" and in the ATDF spec example is shown with multiple chars.
So after reading multiple time the description how 3 bits in the TEST_FLG  and PARM_FLG  field should be written into a single char, I decided to implemented by the following way:
1. If TEST_FLG bit 6 value is 1 -> the output is empty space ' ' (Test completed without pass/fail indication). END.
2. If TEST_FLG bit 6 value is 0, that means that bit 7 is valid. Continue to point 3.
3. If TEST_FLG bit 7 value is 1 -> the output value is 'F' (Test failed). END.
4. If TEST_FLG bit 7 value is 0, the value from PARM_FLG bit 5 will be taken. Continue to point 5.
5. If PARM_FLG bit 5 value is 0 -> the output is 'P' (Test failed or test passed standard limits). END.
6. If PARM_FLG bit 5 value is 1 -> the output is 'A' (Test passed alternate limits). END.

Let me know if this sound logical for you.

I will push the new release to pip in the next minutes.

Regards,
Seimit
