### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by AnouarBenQ** [Semi-ATE/STDF#54]
Reading a standard STDF generated the error : UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
something to do with the encoding

code snippet:
for REC in STDF.records_from_file(file):
    print(REC)

**Comment by seimit** [comment]
Hello,
Could you provide the STDF file?
Regards!
Seimit

**Comment by AnouarBenQ** [comment]
Hi Seimit the STDF file was corrupted hence the error, thanks

**Comment by AnouarBenQ** [comment]
Hello there, Sorry for not replying sooner, the issue occurred because the STDF file was corrupt.
Thanks for your feedback.
